### ISSUE TITLE
Have never been able to get macros working

### ISSUE THREAD

**Issue by joewang704** [WootingKb/wooting-macros#167] opened 2023-08-31 20:15 UTC
I've created fairly simple macros. Input is either a key or CTRL + a key and then output should be spaces/any key pressed multiple times. This has never worked.

**Comment by medzernik** [comment] 2023-11-09 11:56
Duplicate of #105

**Comment by medzernik** [comment] 2023-11-09 12:04
> I've created fairly simple macros. Input is either a key or CTRL + a key and then output should be spaces/any key pressed multiple times. This has never worked.

Might be related to #171

**Comment by medzernik** [comment] 2024-03-01 13:56
Can you please try 1.1 and see if you still have the issue? @joewang704

**Closed** 2024-03-05 11:12 UTC
Labels: bug
